version: "3"
services:
  api:
    container_name: superformula-users-api
    restart: always
    build: .
    environment:
      - USERS_API_HOST=0.0.0.0
      - USERS_API_PORT=8081
    ports:
      - "8081:8081"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"