/**
 * A single user object model
 * @type {Object: User} 
 */
module.exports = {
  "id": "xxx",                  // Unique GUID, generated by the API when creating a user
  "name": null,                 // user's name
  "dob": null,                  // date of birth in ISO format
  "address": null,              // user address string
  "description": null,          // user description
  "createdAt": null,            // user created date
  "updatedAt": null             // user updated date
}